[package]
name = "foreman"
version = "0.1.0"
authors = ["Paul Delafosse <paul.delafosse@protonmail.com>"]
edition = "2018"

[dependencies]
reqwest = "0.9.22"
config = "0.9.3"
clap = "2.33.0"
serde = "^1"
serde_json = "^1"
serde_derive = "^1.0"
short-crypt = "1.0.14"
termion = "1.5.3"
rand = "0.7.2"